# Use root/example as user/password credentials
version: '3.1'

services:
  taskmanager.db:
    image: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: password}
      MYSQL_ROOT_USER: root
      MYSQL_USER: taskmanager_user
      MYSQL_DATABASE: taskmanager_db
      MYSQL_PASSWORD: password}
    #ports:
    #  - 33061:3306
  taskmanager.app:
    image: openjdk:17
    ports:
      - 8089:8080
    volumes:
      - ./target/taskmanager.jar:/app.jar
    entrypoint: java -jar /app.jar --spring.profiles.active=LOCAL